services:
  - type: web
    name: tarangini-jewels
    runtime: docker
    plan: free

    # All setup (composer, migrations, cache) is now in the Dockerfile,
    # making buildCommand minimal or empty.
    buildCommand: ""
    startCommand: "" # Leave empty, the Docker CMD handles the server startup

    envVars:
      - key: APP_URL
        value: https://tarangini-jewels.onrender.com
      - key: PORT
        value: 8080 # Important: Match the EXPOSE port in your Dockerfile
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      # ... database variables (DB_CONNECTION, DB_HOST, DB_DATABASE, etc.)
