services:
  - type: web
    name: tarangini-jewels
    runtime: docker
    plan: free

    # Set the entrypoint to your custom start script
    startCommand: ./start.sh

    # Add your required environment variables
    envVars:
      - key: APP_URL
        value: https://tarangini-jewels.onrender.com
      - key: PORT
        value: 8080 # Matches the EXPOSE 8080 in the Dockerfile
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

      # Laravel requires a key for encryption (Render will generate it)
      - key: APP_KEY
        generateValue: true


