services:
  - type: web
    name: tarangini-jewels
    runtime: docker # IMPORTANT: Use 'docker' for PHP apps on Render
    plan: free

    # buildCommand and startCommand are now empty because all logic is in the Dockerfile
    buildCommand: ""
    startCommand: ""

    # Add your required environment variables
    envVars:
      - key: APP_URL
        value: https://tarangini-jewels.onrender.com
      - key: PORT
        value: 8080 # Matches the EXPOSE 8080 in the Dockerfile
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

      # Laravel requires a key for encryption (Render will generate it)
      - key: APP_KEY
        generateValue: true


